### ISSUE TITLE
Support for writing checksums

### ISSUE THREAD

**Issue by ghost** [cavaliercoder/go-cpio#7]
Hello,
I'm trying to integrate go-cpio into my application. The application used to be written in bash but I'm porting it to go. In the bash version I'd call `cpio -ov -H crc > "filename"` to add the files to the archive. With go-cpio, I add the file contents similarly to how you do in the Readme (without saving the files to disk first).
The header that results has a magic sequence of 070701, which I see is hardcoded in svr4Magic.

Is there a way to set the magic sequence to 070702?

I also set the header's Checksum before writing it to the archive, but the sum doesn't end up in the final cpio header. I'm not sure if my application requires the checksum but thought I should point it out anyway, in case it was accidentally left out.

Thanks,
Spencer

**Comment by ghost** [comment]
Follow-up: I think my application does require the Checksum to be in the header. Per [swupdate's documentation](https://sbabic.github.io/swupdate/swupdate.html?highlight=cpio#what-is-expected-from-a-swupdate-run): 

> Reads the cpio archive and proofs the checksum of each single file SWUpdate stops if the archive is not complete verified

**Comment by cavaliercoder** [comment]
Unfortunately, for now, this lib doesn't support writing archives with checksums. It probably should! PRs are welcome. Otherwise, I'll try find time to implement this.

**Comment by cavaliercoder** [comment]
Closed by #8.
